### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by fege** [fege/soccer-py#2]
- [ ] add tests for this first call
- [ ] add all other calls with tests to the api
- [ ] create a client (cmd line or web???)
